### ISSUE TITLE
Support for running in github actions

### ISSUE THREAD

**Issue by danobi** [linux-kdevops/kdevops-history#7]
Hi,

Josef pointed me towards this project after I proposed a
virtual machine based testing topic for LSFMMBPF:

https://lore.kernel.org/bpf/f1ea109c-5f07-4734-83f5-12c4252fa5ae@app.fastmail.com/

I've been reading through some of the docs here and there's one
thing that's unclear to me: whether nor not kdevops can run in
github actions (or gitlab CI; whichever you prefer).

Has anyone tried before / is there any interest in gaining support
for that?

Thanks in advance.

**Comment by mcgrof** [comment]
Sorry I don't check web GUI stuff, so for a future more timely response best is to email folks directly involved with the project (git shortlog -sne v5.0.2..    gives a good list) and Cc patches@lists.linux.dev as that will archive all email on lore and is project agnostic. 

Yes I added some basic .travis.yml stuff to support 'make python-tests' so we can expand on that list to run other tests. Whatever we can would be awesome.
